version: "3.7"
services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_doctor
      MYSQL_USER: doctor
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456